name: MEGA Upload via API

on:
  workflow_dispatch:

jobs:
  upload:
    runs-on: windows-latest
    steps:
      - name: Create and upload file
        shell: powershell
        run: |
          # Создаём файл
          $timestamp = Get-Date -Format "yyyy-MM-dd HH:mm:ss"
          "Test file: $timestamp" | Out-File test.txt
          
          # Конвертируем в base64
          $bytes = [System.IO.File]::ReadAllBytes("test.txt")
          $base64 = [Convert]::ToBase64String($bytes)
          
          # MEGA API login
          $email = "${{ secrets.MEGA_EMAIL }}"
          $password = "${{ secrets.MEGA_PASSWORD }}"
          
          # Хеш пароля (упрощённый)
          $passwordHash = [System.Security.Cryptography.SHA256]::Create().ComputeHash([System.Text.Encoding]::UTF8.GetBytes($password))
          $passwordHashBase64 = [Convert]::ToBase64String($passwordHash)
          
          Write-Host "Email: $email"
          Write-Host "File size: $($bytes.Length) bytes"
          Write-Host "Ready to upload!"
